# Generated by Django 5.0.6 on 2024-06-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='publishedAt',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='newsarticle',
            old_name='urlToImage',
            new_name='url_to_image',
        ),
    ]
